main: net.minesky.mineskygameplay.MineSkyGameplay
name: MineSkyGameplay
api-version: '26.1.2'

version: '${version}'

folia-supported: true
load: POSTWORLD

softdepend:
  - floodgate

commands:
  conquistas:
    aliases:
      - conquista
      - achievments