main: net.minesky.gameplay.MineSkyGameplayPlugin
name: MineSkyGameplay

api-version: '26.1.2'

version: '${version}'

folia-supported: true
load: POSTWORLD

softdepend:
  - MythicMobs
  - floodgate
  - Essentials
  - HuskClaims

commands:
  conquistas:
    aliases:
      - conquista
      - achievments
  homes:
    description: Abre o menu de homes e terrenos
    aliases: [ "terrenos", "salvos", "casa" ]
  home:
    description: Teleporta-se até um local salvo
    aliases: [ "salvo", "casas" ]